这样我们可以创建一个numpy数组。但是numpy的数组和Python原生的列表数据结构并不相同，它不能直接append、pop等。并且在numpy数组中，元素的数据类型必须要统一，不允许多个不同类型数据存放在同一个数组当中。那numpy数组具备怎样的特性呢？在后面我们会看到，numpy.array很重要的特性就是它可以模拟线性代数当中的各种运算。

这样，我们创建了一个数据类型为numpy.int32类型的数组。

numpy数组与其他数据类型之间也可以进行方便的数据转换。例如，列表、元组可以转换为numpy.array，而numpy.array也可以转换为列表等数据结构。例如，我们有两种方法把上述数组修改为Python列表类型：

In [1]:
# 方法1：直接强制类型转换：
x=list(x)
# 方法2：使用tolist方法
x=x.tolist()


NameError: name 'x' is not defined

In [2]:
import numpy as np

# 创建一个2x3的零矩阵
zero_matrix = np.zeros((2, 3))
print(zero_matrix)
# 输出:
# [[0. 0. 0.]
#  [0. 0. 0.]]


[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
import numpy as np

# 创建一个2x3的数组，所有元素都是42
full_matrix = np.full((2, 3), 42)
print(full_matrix)
# 输出:
# [[42 42 42]
#  [42 42 42]]


[[42 42 42]
 [42 42 42]]


In [4]:
import numpy as np

# 生成从0到5（不包括5）的数组，步长为1
arange_array = np.arange(0, 5)
print(arange_array)
# 输出:
# [0 1 2 3 4]

# 生成从0到10的数组，步长为2
arange_step_array = np.arange(0, 11, 2)
print(arange_step_array)
# 输出:
# [ 0  2  4  6  8 10]


[0 1 2 3 4]
[ 0  2  4  6  8 10]


In [5]:
import numpy as np

# 创建一个二维数组
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# 使用.T属性进行转置
arr_T = arr.T

print(arr_T)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


在NumPy中，改变数组的形状通常是通过reshape函数来实现的。reshape函数允许你在不改变数组数据的情况下，重新排列数组的元素以形成新的形状。这要求新形状的总元素数量与原始数组的总元素数量相同。

In [7]:
import numpy as np

# 创建一个一维数组
arr = np.arange(6)  # array([0, 1, 2, 3, 4, 5])

# 使用reshape重塑为2x3的二维数组
arr_reshaped = arr.reshape((2, 3))

print(arr_reshaped)
# 输出:
# [[0 1 2]
#  [3 4 5]]


[[0 1 2]
 [3 4 5]]


原始数组的总元素数量必须与新形状的总元素数量相匹配，否则reshape会抛出异常。
使用-1作为newshape中的一个维度可以让NumPy自动计算该维度的大小。这在你不知道某个维度具体大小但知道其他维度大小时非常有用。

In [8]:
import numpy as np  
  
# 创建一个二维数组  
arr = np.array([[1, 2, 3], [4, 5, 6]])  
  
# 使用flatten转换为一维数组  
arr_flat = arr.flatten()  # 注意：这里也可以直接使用 np.flatten(arr)，但使用数组对象的方法更常见  
  
print(arr_flat)  
# 输出:  
# [1 2 3 4 5 6]


[1 2 3 4 5 6]


In [9]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# 默认沿着第一个轴（axis=0）拼接
c = np.concatenate((a, b), axis=0)
print(c)
# 输出:
# [[1 2]
#  [3 4]
#  [5 6]]

# 沿着第二个轴（axis=1）拼接
d = np.concatenate((a, b.T), axis=1)  # 注意b需要转置以匹配a的形状
print(d)
# 输出:
# [[1 2 5]
#  [3 4 6]]


[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


在NumPy中，数组（尤其是ndarray对象）通常被设计为固定大小的，这意呀着它们不像Python的列表（list）那样可以方便地追加或删除元素。然而，NumPy提供了一些方法来间接实现这些操作，但通常这些方法会涉及到创建新的数组，而不是在原地修改原始数组。

In [10]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5])

# 沿着第一个轴（axis=0）追加
c = np.concatenate((a, b))
print(c)  # 输出: [1 2 3 4 5]


[1 2 3 4 5]


在NumPy中删除元素通常意味着创建一个新的数组，它包含了除了要删除的元素之外的所有元素。这可以通过布尔索引、切片或numpy.delete()函数来实现。

In [11]:
a = np.array([1, 2, 3, 4, 5])

# 删除值为3的元素
mask = a != 3
b = a[mask]
print(b)  # 输出: [1 2 4 5]


[1 2 4 5]


In [12]:
a = np.array([1, 2, 3, 4, 5])

# 跳过第三个元素
b = np.concatenate((a[:2], a[3:]))
print(b)  # 输出: [1 2 4 5]


[1 2 4 5]


这些操作都会返回一个新的数组，而不是修改原始数组。
对于大型数组，频繁地创建新数组（尤其是在循环中）可能会导致性能问题。在这些情况下，考虑是否可以使用更高效的算法或数据结构，或者是否可以将数据转换为更适合追加和删除操作的形式（如Python列表）。
numpy.append()和numpy.delete()虽然方便，但在处理大数据集时可能不是最高效的方法。在这些情况下，考虑使用布尔索引或切片等更底层的方法。

广播机制是NumPy在算术运算中处理不同形状数组的一种方式，它允许在不进行显式复制数据的情况下执行元素级别的操作，从而提高了代码的执行效率和可读性。当两个或多个数组的形状不一致时，NumPy会尝试通过广播机制将它们“扩展”到相同的形状，以便可以进行逐元素的算术运算。

在NumPy中，当两个或多个数组的形状不一致，但满足广播规则时，就会发生数组广播。具体来说，如果两个数组在维度上不匹配，但满足以下条件之一，就可以通过广播机制进行运算：

维度较小的数组会在前面补1，使得两个数组的维度数相同。
在某个维度上，如果一个数组的大小为1，则它会被视为在该维度上重复扩展，以匹配另一个数组的大小。
如果两个数组在所有维度上都不匹配，并且没有任何一个维度的大小为1，则无法进行广播，并会引发错误。

In [15]:
import numpy as np

A = np.array([1, 2, 3])  # 形状 (3,)
B = np.array([10, 20, 30, 40])  # 形状 (4,)

# 尝试进行加法运算，但直接相加会报错，因为形状不匹配
# 但如果我们将A视为 (1, 3) 形状的数组，并将B视为 (4, 1) 形状的数组，然后进行逐元素加法，则可以实现广播
# 然而，NumPy不会直接显示地改变数组的形状，而是隐式地进行广播

# 实际上，NumPy不允许直接将形状为 (3,) 和 (4,) 的数组进行广播
# 但如果我们将B的前三个元素与A的元素相加，可以模拟广播的效果（注意：这不是NumPy的默认行为）
# 为了演示广播，我们可以使用形状兼容的数组
C = np.array([10, 20, 30])  # 形状 (3,)
D = A + C  # 这里可以广播，因为形状相同
print(D)  # 输出: [11 22 33]

# 注意：上面的C和D的示例是为了说明广播的概念，而不是NumPy直接允许的操作


[11 22 33]


In [16]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])  # 形状 (2, 3)
B = np.array([10, 20, 30])  # 形状 (3,)

# B会被视为形状为 (1, 3) 的数组，然后在第一个维度上复制以匹配A的形状 (2, 3)
# 现在A和B具有相同的“广播后”形状，可以进行逐元素加法
C = A + B
print(C)
# 输出:
# [[11 22 33]
#  [14 25 36]]


[[11 22 33]
 [14 25 36]]


<div style="border: 2px solid #ccc; background-color: #f9f9f9; padding: 15px; border-radius: 5px; margin: 10px 0;">
<strong>numpy.random.rand()</strong><br>
功能：生成指定形状的数组，数组中的元素在区间[0, 1)内均匀分布。<br><br>
<strong>numpy.random.randn()</strong><br>
功能：生成指定形状的数组，数组中的元素服从标准正态分布（均值为0，标准差为1）。<br><br>
<strong>numpy.random.randint()</strong><br>
功能：生成指定范围内的随机整数数组。可以指定范围的最小值、最大值和数组的形状。
</div>

In [18]:
import numpy as np

# 生成一个具有5个元素的一维数组
arr1 = np.random.rand(5)
print(arr1)

# 生成一个2行3列的二维数组
arr2 = np.random.randn(2, 3)
print(arr2)


[0.45272206 0.13769092 0.6732302  0.18519978 0.61203859]
[[-1.01434513  0.59465274 -1.0085644 ]
 [ 0.47398574 -0.46846588 -0.78918982]]


在Numpy中实现向量的数量积，可以使用numpy.dot()函数或@操作符。这两个操作在处理一维数组（可以视为向量）时，都会计算它们的点积（即数量积）。


In [20]:
# 假设我们有一个数组
arr = np.array([1, 2, 3, 4, 5, 6])

# 筛选所有大于3的元素
filtered_arr = arr[arr > 3]
print("Filtered array:", filtered_arr)


Filtered array: [4 5 6]


In [21]:
# 创建一个二维数组
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 筛选所有行，其中第一个元素大于3且第二个元素小于8
# 注意使用&和括号
filtered_rows = arr_2d[(arr_2d[:, 0] > 3) & (arr_2d[:, 1] < 8)]
print("Filtered rows:", filtered_rows)

# 或者使用numpy.logical_and()
filtered_rows_logical = arr_2d[np.logical_and(arr_2d[:, 0] > 3, arr_2d[:, 1] < 8)]
print("Filtered rows with logical_and:", filtered_rows_logical)


Filtered rows: [[4 5 6]]
Filtered rows with logical_and: [[4 5 6]]


In [22]:
# 假设我们有一个表示学生分数的二维数组
scores = np.array([[85, 92], [78, 85], [90, 95], [55, 60]])

# 筛选数学成绩（第二列）大于80的所有行
high_math_scores = scores[scores[:, 1] > 80]
print("Students with high math scores:", high_math_scores)


Students with high math scores: [[85 92]
 [78 85]
 [90 95]]
