这样我们可以创建一个numpy数组。但是numpy的数组和Python原生的列表数据结构并不相同，它不能直接append、pop等。并且在numpy数组中，元素的数据类型必须要统一，不允许多个不同类型数据存放在同一个数组当中。那numpy数组具备怎样的特性呢？在后面我们会看到，numpy.array很重要的特性就是它可以模拟线性代数当中的各种运算。

这样，我们创建了一个数据类型为numpy.int32类型的数组。

numpy数组与其他数据类型之间也可以进行方便的数据转换。例如，列表、元组可以转换为numpy.array，而numpy.array也可以转换为列表等数据结构。例如，我们有两种方法把上述数组修改为Python列表类型：

In [24]:
# 方法1：直接强制类型转换：
x=list(x)
# 方法2：使用tolist方法
x=x.tolist()


NameError: name 'x' is not defined

In [25]:
import numpy as np

# 创建一个2x3的零矩阵
zero_matrix = np.zeros((2, 3))
print(zero_matrix)
# 输出:
# [[0. 0. 0.]
#  [0. 0. 0.]]


[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
import numpy as np

# 创建一个2x3的数组，所有元素都是42
full_matrix = np.full((2, 3), 42)
print(full_matrix)
# 输出:
# [[42 42 42]
#  [42 42 42]]


[[42 42 42]
 [42 42 42]]


In [27]:
import numpy as np

# 生成从0到5（不包括5）的数组，步长为1
arange_array = np.arange(0, 5)
print(arange_array)
# 输出:
# [0 1 2 3 4]

# 生成从0到10的数组，步长为2
arange_step_array = np.arange(0, 11, 2)
print(arange_step_array)
# 输出:
# [ 0  2  4  6  8 10]


[0 1 2 3 4]
[ 0  2  4  6  8 10]


In [28]:
import numpy as np

# 创建一个二维数组
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# 使用.T属性进行转置
arr_T = arr.T

print(arr_T)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


在NumPy中，改变数组的形状通常是通过reshape函数来实现的。reshape函数允许你在不改变数组数据的情况下，重新排列数组的元素以形成新的形状。这要求新形状的总元素数量与原始数组的总元素数量相同。

In [29]:
import numpy as np

# 创建一个一维数组
arr = np.arange(6)  # array([0, 1, 2, 3, 4, 5])

# 使用reshape重塑为2x3的二维数组
arr_reshaped = arr.reshape((2, 3))

print(arr_reshaped)
# 输出:
# [[0 1 2]
#  [3 4 5]]


[[0 1 2]
 [3 4 5]]


原始数组的总元素数量必须与新形状的总元素数量相匹配，否则reshape会抛出异常。
使用-1作为newshape中的一个维度可以让NumPy自动计算该维度的大小。这在你不知道某个维度具体大小但知道其他维度大小时非常有用。

In [30]:
import numpy as np  
  
# 创建一个二维数组  
arr = np.array([[1, 2, 3], [4, 5, 6]])  
  
# 使用flatten转换为一维数组  
arr_flat = arr.flatten()  # 注意：这里也可以直接使用 np.flatten(arr)，但使用数组对象的方法更常见  
  
print(arr_flat)  
# 输出:  
# [1 2 3 4 5 6]


[1 2 3 4 5 6]


In [31]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# 默认沿着第一个轴（axis=0）拼接
c = np.concatenate((a, b), axis=0)
print(c)
# 输出:
# [[1 2]
#  [3 4]
#  [5 6]]

# 沿着第二个轴（axis=1）拼接
d = np.concatenate((a, b.T), axis=1)  # 注意b需要转置以匹配a的形状
print(d)
# 输出:
# [[1 2 5]
#  [3 4 6]]


[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


在NumPy中，数组（尤其是ndarray对象）通常被设计为固定大小的，这意呀着它们不像Python的列表（list）那样可以方便地追加或删除元素。然而，NumPy提供了一些方法来间接实现这些操作，但通常这些方法会涉及到创建新的数组，而不是在原地修改原始数组。

In [32]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5])

# 沿着第一个轴（axis=0）追加
c = np.concatenate((a, b))
print(c)  # 输出: [1 2 3 4 5]


[1 2 3 4 5]


在NumPy中删除元素通常意味着创建一个新的数组，它包含了除了要删除的元素之外的所有元素。这可以通过布尔索引、切片或numpy.delete()函数来实现。

In [33]:
a = np.array([1, 2, 3, 4, 5])

# 删除值为3的元素
mask = a != 3
b = a[mask]
print(b)  # 输出: [1 2 4 5]


[1 2 4 5]


In [34]:
a = np.array([1, 2, 3, 4, 5])

# 跳过第三个元素
b = np.concatenate((a[:2], a[3:]))
print(b)  # 输出: [1 2 4 5]


[1 2 4 5]


这些操作都会返回一个新的数组，而不是修改原始数组。
对于大型数组，频繁地创建新数组（尤其是在循环中）可能会导致性能问题。在这些情况下，考虑是否可以使用更高效的算法或数据结构，或者是否可以将数据转换为更适合追加和删除操作的形式（如Python列表）。
numpy.append()和numpy.delete()虽然方便，但在处理大数据集时可能不是最高效的方法。在这些情况下，考虑使用布尔索引或切片等更底层的方法。

广播机制是NumPy在算术运算中处理不同形状数组的一种方式，它允许在不进行显式复制数据的情况下执行元素级别的操作，从而提高了代码的执行效率和可读性。当两个或多个数组的形状不一致时，NumPy会尝试通过广播机制将它们“扩展”到相同的形状，以便可以进行逐元素的算术运算。

在NumPy中，当两个或多个数组的形状不一致，但满足广播规则时，就会发生数组广播。具体来说，如果两个数组在维度上不匹配，但满足以下条件之一，就可以通过广播机制进行运算：

维度较小的数组会在前面补1，使得两个数组的维度数相同。
在某个维度上，如果一个数组的大小为1，则它会被视为在该维度上重复扩展，以匹配另一个数组的大小。
如果两个数组在所有维度上都不匹配，并且没有任何一个维度的大小为1，则无法进行广播，并会引发错误。

In [35]:
import numpy as np

A = np.array([1, 2, 3])  # 形状 (3,)
B = np.array([10, 20, 30, 40])  # 形状 (4,)

# 尝试进行加法运算，但直接相加会报错，因为形状不匹配
# 但如果我们将A视为 (1, 3) 形状的数组，并将B视为 (4, 1) 形状的数组，然后进行逐元素加法，则可以实现广播
# 然而，NumPy不会直接显示地改变数组的形状，而是隐式地进行广播

# 实际上，NumPy不允许直接将形状为 (3,) 和 (4,) 的数组进行广播
# 但如果我们将B的前三个元素与A的元素相加，可以模拟广播的效果（注意：这不是NumPy的默认行为）
# 为了演示广播，我们可以使用形状兼容的数组
C = np.array([10, 20, 30])  # 形状 (3,)
D = A + C  # 这里可以广播，因为形状相同
print(D)  # 输出: [11 22 33]

# 注意：上面的C和D的示例是为了说明广播的概念，而不是NumPy直接允许的操作


[11 22 33]


In [36]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])  # 形状 (2, 3)
B = np.array([10, 20, 30])  # 形状 (3,)

# B会被视为形状为 (1, 3) 的数组，然后在第一个维度上复制以匹配A的形状 (2, 3)
# 现在A和B具有相同的“广播后”形状，可以进行逐元素加法
C = A + B
print(C)
# 输出:
# [[11 22 33]
#  [14 25 36]]


[[11 22 33]
 [14 25 36]]


<div style="border: 2px solid #ccc; background-color: #f9f9f9; padding: 15px; border-radius: 5px; margin: 10px 0;">
<strong>numpy.random.rand()</strong><br>
功能：生成指定形状的数组，数组中的元素在区间[0, 1)内均匀分布。<br><br>
<strong>numpy.random.randn()</strong><br>
功能：生成指定形状的数组，数组中的元素服从标准正态分布（均值为0，标准差为1）。<br><br>
<strong>numpy.random.randint()</strong><br>
功能：生成指定范围内的随机整数数组。可以指定范围的最小值、最大值和数组的形状。
</div>

In [37]:
import numpy as np

# 生成一个具有5个元素的一维数组
arr1 = np.random.rand(5)
print(arr1)

# 生成一个2行3列的二维数组
arr2 = np.random.randn(2, 3)
print(arr2)


[0.18966066 0.64231357 0.04800905 0.96063125 0.59462212]
[[-1.22864435  1.14430895 -1.50708015]
 [ 1.06728043 -0.42005099 -1.0331468 ]]


在Numpy中实现向量的数量积，可以使用numpy.dot()函数或@操作符。这两个操作在处理一维数组（可以视为向量）时，都会计算它们的点积（即数量积）。


In [38]:
# 假设我们有一个数组
arr = np.array([1, 2, 3, 4, 5, 6])

# 筛选所有大于3的元素
filtered_arr = arr[arr > 3]
print("Filtered array:", filtered_arr)


Filtered array: [4 5 6]


In [39]:
# 创建一个二维数组
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 筛选所有行，其中第一个元素大于3且第二个元素小于8
# 注意使用&和括号
filtered_rows = arr_2d[(arr_2d[:, 0] > 3) & (arr_2d[:, 1] < 8)]
print("Filtered rows:", filtered_rows)

# 或者使用numpy.logical_and()
filtered_rows_logical = arr_2d[np.logical_and(arr_2d[:, 0] > 3, arr_2d[:, 1] < 8)]
print("Filtered rows with logical_and:", filtered_rows_logical)


Filtered rows: [[4 5 6]]
Filtered rows with logical_and: [[4 5 6]]


In [40]:
# 假设我们有一个表示学生分数的二维数组
scores = np.array([[85, 92], [78, 85], [90, 95], [55, 60]])

# 筛选数学成绩（第二列）大于80的所有行
high_math_scores = scores[scores[:, 1] > 80]
print("Students with high math scores:", high_math_scores)


Students with high math scores: [[85 92]
 [78 85]
 [90 95]]


In [42]:
import numpy as np

# 创建一个数组
arr = np.array([1, 2, 3, 4, 5, 6])

# 使用 np.where() 找到所有大于3的元素的索引
indices = np.where(arr > 3)
print("Indices of elements greater than 3:", indices)

# 如果你想要基于条件获取实际的元素值
filtered_values = arr[arr > 3]
print("Values greater than 3:", filtered_values)



Indices of elements greater than 3: (array([3, 4, 5], dtype=int64),)
Values greater than 3: [4 5 6]


In [43]:
import numpy as np

# 创建一个二维数组，表示三位同学的三门课成绩
arr = np.array([[85, 92, 88],
                [78, 90, 85],
                [90, 87, 92]])


In [44]:
mean_each_subject = np.mean(arr, axis=0)
print("每门课的平均成绩:", mean_each_subject)  # 输出: 每门课的平均成绩: [84.33333333 89.66666667 88.33333333]


每门课的平均成绩: [84.33333333 89.66666667 88.33333333]


In [45]:
sum_each_subject = np.sum(arr, axis=0)
print("每门课的总成绩:", sum_each_subject)  # 输出: 每门课的总成绩: [262 269 265] 注意这里应该是[263 267 265]，但考虑到浮点数的精度问题，可能会有微小差异


每门课的总成绩: [253 269 265]


In [48]:
import numpy as np

# 创建两个数组
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

# 进行数组加法运算
result_array = array1 + array2

# 打印结果，查看加法运算后的数组
print("加法运算结果：", result_array)

# 使用np.savetxt保存结果到文本文件
# 假设我们要将结果保存到名为'result.txt'的文件中
np.savetxt('result.txt', result_array, fmt='%d', delimiter=',', newline='\n')

# 注意：fmt参数指定了每个元素的格式，这里是整数'%d'
# delimiter参数指定了元素之间的分隔符，这里是逗号','
# newline参数指定了每行结束后的换行符，这里是换行符'\n'
# 这些参数可以根据需要进行调整


加法运算结果： [6 6 6 6 6]


在上述例子中，我们首先创建了两个一维数组array1和array2，并进行了加法运算，得到了结果数组result_array。然后，我们使用np.savetxt函数将result_array保存到名为result.txt的文本文件中。在np.savetxt函数中，我们通过fmt参数指定了每个元素的格式（这里是整数格式'%d'），通过delimiter参数指定了元素之间的分隔符（这里是逗号,），以及通过newline参数指定了每行结束后的换行符（这里是换行符\n）。

np.savetxt是一个非常灵活的函数，支持多种参数来定制输出文件的格式。除了上面提到的fmt、delimiter和newline参数外，还有一些其他常用的参数：

header：用于在文件顶部添加注释或标题行。
footer：用于在文件底部添加文本。
comments：指定注释字符，默认为'# '。如果header或footer参数中包含该字符，它们将被视为注释。

In [49]:
# 使用loadtxt加载之前保存的数组  
# 根据保存时指定的格式和分隔符来加载  
loaded_arr = np.loadtxt('array_data.txt', delimiter=',', dtype=float)  
  
# 如果你保存时没有指定fmt或者delimiter，这里也需要相应地调整  
# 比如，如果默认分隔符是空格，且没有指定fmt  
# loaded_arr = np.loadtxt('array_data_no_fmt.txt', dtype=float)  
  
# 打印加载的数组来验证  
print(loaded_arr)


FileNotFoundError: array_data.txt not found.

<div style="border: 2px solid #ccc; background-color: #f9f9f9; padding: 15px; border-radius: 5px; margin: 10px 0;">
首先我们来看看矩阵的求逆。<br><br>
逆矩阵是线性代数中的一个基本概念，主要用于解线性方程组、矩阵的分解以及计算机图形学等领域。对于一个给定的方阵（即行数和列数相等的矩阵）$A$，如果存在另一个方阵 $B$，使得 $AB = BA = I$（其中 $I$ 是单位矩阵，即对角线上元素为1，其余元素为0的矩阵），则称 $B$ 为 $A$ 的逆矩阵，记作 $A^{-1}$。<br><br>
逆矩阵的求法可以用很多方法求，其中比较典型的包括：
</div>

In [51]:
import numpy as np

# 定义一个方阵A
A = np.array([[1, 2], [3, 4]])

# 计算A的逆矩阵
A_inv = np.linalg.inv(A)

print("矩阵A:")
print(A)
print("矩阵A的逆矩阵:")
print(A_inv)

# 验证A * A_inv 是否等于单位矩阵
I = np.dot(A, A_inv)
print("A * A_inv =")
print(I)


矩阵A:
[[1 2]
 [3 4]]
矩阵A的逆矩阵:
[[-2.   1. ]
 [ 1.5 -0.5]]
A * A_inv =
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


而伪逆矩阵的出现，主要是为了解决在线性代数中遇到的一些问题，特别是在处理非方阵（即行数和列数不相等的矩阵）或奇异矩阵（即行列式为0的方阵）时，这些矩阵没有传统意义上的逆矩阵。伪逆矩阵提供了一种在这些情况下求解线性方程组或最小化二乘误差的方法。

在NumPy库中，np.linalg.pinv函数用于计算矩阵的伪逆。这个函数可以处理非方阵和奇异矩阵，并返回它们的伪逆矩阵。

矩阵的秩是线性代数中的一个重要概念，它表示矩阵中行或列之间的线性关系。具体来说，矩阵的秩定义为该矩阵所有子式中非零子式的最高阶数。换句话说，如果我们从矩阵中挑选出一些行和列，组成一个子式，那么这个子式的阶数最大能是多少，这个数就是矩阵的秩。在另一种等价定义中，矩阵的秩也可以理解为矩阵中独立行（或列）的数量，即矩阵的行向量组（或列向量组）的秩。

矩阵的秩有很多重要的性质和应用，比如它可以用于判断矩阵是否可逆（非零方阵的秩等于其阶数时，矩阵可逆），以及确定线性方程组解的存在性和唯一性（如果系数矩阵的秩小于增广矩阵的秩，则方程组无解；如果系数矩阵的秩等于方程个数，则方程组有唯一解；如果系数矩阵的秩小于方程个数，则方程组有无穷多解）。

In [52]:
import numpy as np

# 定义一个矩阵
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 计算矩阵的秩
rank = np.linalg.matrix_rank(matrix)

print("矩阵的秩为:", rank)


矩阵的秩为: 2


In [53]:
import numpy as np

# 创建一个3x3的矩阵
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])

# 计算矩阵的行列式
det = np.linalg.det(matrix)

# 输出结果
print("矩阵:\n", matrix)
print("行列式:", det)


矩阵:
 [[1 2 3]
 [4 5 6]
 [7 8 0]]
行列式: 27.0


<div style="border: 2px solid #ccc; background-color: #f9f9f9; padding: 15px; border-radius: 5px; margin: 10px 0;">
矩阵范数用于衡量矩阵的“大小”或“规模”。它是一个将矩阵映射到非负实数的函数，满足一系列特定的性质，如非负性、齐次性、三角不等式等。矩阵范数有多种定义方式，常见的有L1范数、L2范数（也称为弗罗贝尼乌斯范数）、无穷范数等。<br><br>
以弗罗贝尼乌斯范数为例，对于矩阵 $A \in \mathbb{R}^{m \times n}$，其弗罗贝尼乌斯范数定义为：
$$
\|A\|_F = \sqrt{\sum_{i=1}^m \sum_{j=1}^n |a_{ij}|^2}
$$
其中，$a_{ij}$ 是矩阵 $A$ 中第 $i$ 行第 $j$ 列的元素。这个范数实际上是矩阵元素平方和的平方根，类似于向量的欧几里得范数。
</div>

In [55]:
a=np.array([[1,2],[3,4]])
norm=np.linalg.norm(a)#计算范数
print(norm)

5.477225575051661


<div style="border: 2px solid #ccc; background-color: #f9f9f9; padding: 15px; border-radius: 5px; margin: 10px 0;">
克拉默法则是线性代数中一个用于求解线性方程组（方程组中方程的个数与未知数的个数相等，且系数矩阵的行列式不为零）的定理。它表述为：如果线性方程组 $Ax = b$ 的系数矩阵 $A$ 是一个 $n \times n$ 矩阵，且 $A$ 的行列式 $|A| \neq 0$，则方程组有唯一解，且解的第 $i$ 个分量 $x_i$ 可以用行列式表示为：<br>
$$
x_i = \frac{\det(A_i)}{\det(A)}
$$
其中，$A_i$ 是将 $A$ 的第 $i$ 列替换为向量 $b$ 后得到的矩阵。<br><br>
由于NumPy库提供了计算行列式的 <code>numpy.linalg.det()</code> 函数，我们可以利用这个函数来实现克拉默法则。
</div>

In [56]:
import numpy as np

def cramer_rule(A, b):
    """
    使用克拉默法则求解线性方程组 Ax = b
    :param A: 系数矩阵，形状为 (n, n)
    :param b: 常数项向量，形状为 (n,)
    :return: 方程组的解，形状为 (n,)
    """
    n = A.shape[0]  # 方程组的未知数个数
    if A.shape[1] != n or b.shape[0] != n:
        raise ValueError("系数矩阵A和常数项向量b的维度不匹配")
    
    det_A = np.linalg.det(A)  # 计算系数矩阵A的行列式
    if det_A == 0:
        raise ValueError("系数矩阵A的行列式为零，方程组无解或有无穷多解")
    
    x = np.zeros(n)  # 初始化解向量
    for i in range(n):
        # 构造矩阵Ai，即将A的第i列替换为b
        Ai = A.copy()
        Ai[:, i] = b
        # 计算Ai的行列式并除以A的行列式得到解的第i个分量
        x[i] = np.linalg.det(Ai) / det_A
    
    return x

# 示例
A = np.array([[4, 3, 2], [2, -2, 4], [3, 8, 2]])
b = np.array([1, 5, 6])

solution = cramer_rule(A, b)
print("方程组的解为:", solution)


方程组的解为: [-1.44736842  0.71052632  2.32894737]


numpy.linalg.solve函数用于求解线性方程组或矩阵方程。给定一个方阵a和一个一维数组b，solve函数会找到x，使得ax = b。这里，a的维度是(n, n)，b的维度是(n,)，解x的维度也将是(n,)。

In [60]:
A = np.array([[4, 3, 2], [2, -2, 4], [3, 8, 2]])
b = np.array([1, 5, 6])
print(np.linalg.solve(A,b))#相当于把上面的事重新做了一遍

[-1.44736842  0.71052632  2.32894737]


<div style="border: 2px solid #ccc; background-color: #f9f9f9; padding: 15px; border-radius: 5px; margin: 10px 0;">
<strong>1. 特征值分解</strong><br>
矩阵的特征值分解（Eigenvalue Decomposition, EVD）是一种将矩阵分解为其特征值和特征向量表示的矩阵之积的方法，也称为谱分解（Spectral Decomposition）。这种方法在数值计算、机器学习、图像处理、计算机视觉等领域有着广泛的应用。<br><br>
设 $A$ 是一个 $n \times n$ 的矩阵，$\lambda$ 是一个数，若存在 $n$ 维非零向量 $x$，使得 $Ax = \lambda x$，则称 $\lambda$ 是矩阵 $A$ 的特征值，$x$ 是 $A$ 对应于 $\lambda$ 的特征向量。矩阵 $A$ 的特征值分解就是将 $A$ 分解为以下形式：<br>
$$
A = U \Lambda U^{-1}
$$
或者，在 $U$ 为正交矩阵（即 $U$ 的列向量是单位向量且两两正交）的情况下，由于正交矩阵的逆等于其转置，上式可以写为：<br>
$$
A = U \Lambda U^T
$$
其中，<br>
<ul>
<li>$U$ 是由 $A$ 的特征向量组成的 $n \times n$ 矩阵，其列向量是 $A$ 的单位化特征向量。</li>
<li>$\Lambda$ 是一个 $n \times n$ 的对角矩阵，其对角线上的元素是 $A$ 的特征值，非对角线上的元素都是 0。</li>
</ul>
<br>
<strong>注意事项</strong><br>
<ul>
<li><strong>特征值与特征向量的关系：</strong>特征值是矩阵中与特定特征向量相关的实数，它表示该特征向量在矩阵变换下的缩放比例。特征向量是矩阵变换中方向不变的向量。</li>
<li><strong>矩阵的可对角化：</strong>只有可对角化矩阵（即存在足够数量的线性无关特征向量的矩阵）才能进行特征值分解。</li>
<li><strong>应用领域：</strong>特征值分解在信号处理、统计学、经济学、量子力学等多个领域都有重要应用。例如，在信号处理中，特征值可以用来分析信号的频率成分；在统计学中，主成分分析（PCA）就是基于特征值分解的一种数据降维方法。</li>
</ul>
在NumPy中，进行特征值分解主要使用 <code>numpy.linalg.eig</code> 函数。这个函数计算给定方阵的特征值和右特征向量。对于对称矩阵（或更一般地，Hermitian矩阵），通常还推荐使用 <code>numpy.linalg.eigh</code>，因为它在数值上更稳定且效率更高。不过，对于非对称矩阵，应使用 <code>numpy.linalg.eig</code>。
</div>

In [64]:
import numpy as np

# 定义一个方阵A
A = np.array([[4, 2], [1, 3]])

# 使用eig函数进行特征值分解
eigenvalues, eigenvectors = np.linalg.eig(A)

# eigenvalues是一个包含特征值的数组
# eigenvectors的列是对应的特征向量

print("特征值：", eigenvalues)
print("特征向量：")
for i, eigenvector in enumerate(eigenvectors.T):
    print(f"特征值 {eigenvalues[i]} 对应的特征向量：{eigenvector}")

# 验证特征值和特征向量的正确性
# 对于每个特征值lambda_i和对应的特征向量v_i，应有 Av_i = lambda_i * v_i
for i, eigenvalue in enumerate(eigenvalues):
    eigenvector = eigenvectors[:, i]
    result = np.dot(A, eigenvector)
    assert np.allclose(result, eigenvalue * eigenvector)
    print(f"验证特征值 {eigenvalue} 和特征向量 {eigenvector} 正确")


特征值： [5. 2.]
特征向量：
特征值 5.0 对应的特征向量：[0.89442719 0.4472136 ]
特征值 2.0 对应的特征向量：[-0.70710678  0.70710678]
验证特征值 5.0 和特征向量 [0.89442719 0.4472136 ] 正确
验证特征值 2.0 和特征向量 [-0.70710678  0.70710678] 正确


<div style="border: 2px solid #ccc; background-color: #f9f9f9; padding: 15px; border-radius: 5px; margin: 10px 0;">
<strong>奇异值分解（Singular Value Decomposition，简称SVD）</strong> 是线性代数中一种重要的矩阵分解方法，它在多个领域如信号处理、统计学等中都有重要应用。以下是奇异值分解的具体定义：<br><br>
奇异值分解是指将一个非零的 $m \times n$ 实矩阵 $A$（其中 $A \in \mathbb{R}^{m \times n}$），表示为以下三个实矩阵乘积形式的运算，即进行矩阵的因子分解：<br>
$$
A = U \Sigma V^T
$$
其中：<br>
<ul>
<li>$U$ 是 $m \times m$ 阶正交矩阵（orthogonal matrix），它的列向量称为<strong>左奇异向量</strong>。</li>
<li>$\Sigma$ 是 $m \times n$ 阶对角矩阵，其对角线上的元素（非负实数）按降序排列，称为<strong>奇异值</strong>。除了对角线上的元素外，$\Sigma$ 的其他位置元素均为 0。</li>
<li>$V$ 是 $n \times n$ 阶正交矩阵，它的列向量称为<strong>右奇异向量</strong>。</li>
<li>$V^T$ 是 $V$ 的转置矩阵。</li>
</ul>
它具备如下一些性质：<br>
<ul>
<li><strong>存在性：</strong>任意 $m \times n$ 的矩阵 $A$ 的奇异值分解一定存在，但可能不唯一（特别是当矩阵 $A$ 存在退化的奇异值时）。</li>
<li><strong>最优近似：</strong>奇异值分解可以被视为在平方损失（Frobenius 范数）意义下对矩阵的最优近似。在实际应用中，常常通过截断奇异值分解（只取最大的 $k$ 个奇异值）来实现矩阵的近似表示，这在数据压缩等领域尤为重要。</li>
<li><strong>几何意义：</strong>从线性变换的角度来看，$m \times n$ 矩阵 $A$ 表示从 $n$ 维空间到 $m$ 维空间的一个线性变换。奇异值分解可以将这个线性变换分解为三个简单的变换：一个坐标系的旋转或反射变换、一个坐标轴的缩放变换（缩放因子即为奇异值）、另一个坐标系的旋转或反射变换。</li>
</ul>
奇异值分解在多个领域有广泛应用，包括但不限于：<br>
<ul>
<li><strong>数据压缩：</strong>通过截断奇异值分解，可以实现对原始数据的近似表示，从而达到数据压缩的目的。</li>
<li><strong>信号处理：</strong>在信号处理中，奇异值分解被用于分析信号的频率成分和进行信号重建。</li>
<li><strong>统计学：</strong>在统计学中，奇异值分解被用于主成分分析（PCA），一种数据降维方法，用于找出数据中的主要模式。</li>
</ul>
</div>

In [72]:
import numpy as np

# 定义一个矩阵A
A = np.array([[1, 2], [3, 4], [5, 6]])

# 使用svd函数进行奇异值分解
U, s, VT = np.linalg.svd(A, full_matrices=False)

# 注意：numpy.linalg.svd返回的s是奇异值数组，而不是对角矩阵
# 我们需要将其转换为对角矩阵形式
Sigma = np.diag(s)  

# VT是V的转置，如果需要V，则可以使用VT.T获取
V = VT.T

# 验证SVD的正确性
# A应该等于U * Sigma * VT（注意Sigma不是方阵时，需要按照形状进行乘法）
reconstructed_A = np.dot(U, np.dot(Sigma, VT))

# 由于浮点运算的精度问题，我们不会直接比较A和reconstructed_A是否相等
# 而是检查它们是否足够接近
print(np.allclose(A, reconstructed_A))  # 应该输出True或非常接近True的值

# 输出奇异值、左奇异向量和右奇异向量
print("奇异值：", s)
print("左奇异向量：")
print(U)
print("右奇异向量：")
print(V)


True
奇异值： [9.52551809 0.51430058]
左奇异向量：
[[-0.2298477   0.88346102]
 [-0.52474482  0.24078249]
 [-0.81964194 -0.40189603]]
右奇异向量：
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
